//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimpYourCharacter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnage()
        {
            this.personnage_tatouage_position = new HashSet<personnage_tatouage_position>();
            this.accessoire = new HashSet<accessoire>();
            this.arme = new HashSet<arme>();
            this.bouclier = new HashSet<bouclier>();
            this.vmain = new HashSet<vmain>();
            this.vpied = new HashSet<vpied>();
            this.vtete = new HashSet<vtete>();
        }
    
        public int id_personnage { get; set; }
        public string nom { get; set; }
        public int age { get; set; }
        public int id_ethnie { get; set; }
        public int id_genre { get; set; }
        public int id_vbas { get; set; }
        public int id_vhaut { get; set; }
        public int id_corps { get; set; }
    
        public virtual corps corps { get; set; }
        public virtual ethnie ethnie { get; set; }
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnage_tatouage_position> personnage_tatouage_position { get; set; }
        public virtual vbas vbas { get; set; }
        public virtual vhaut vhaut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accessoire> accessoire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arme> arme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bouclier> bouclier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vmain> vmain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vpied> vpied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtete> vtete { get; set; }
    }
}
